// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6d7Nq29h6FNB5mHu6qQErT-jRujb_cDE',
    appId: '1:929662936824:web:bbc091adb07f938bdebd0d',
    messagingSenderId: '929662936824',
    projectId: 'easy-stock-micda-16001',
    authDomain: 'easy-stock-micda-16001.firebaseapp.com',
    storageBucket: 'easy-stock-micda-16001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANm5sKqzpyXUAMelARPZtrNpldCbLNeOE',
    appId: '1:929662936824:android:7b7016cab7c66420debd0d',
    messagingSenderId: '929662936824',
    projectId: 'easy-stock-micda-16001',
    storageBucket: 'easy-stock-micda-16001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ9mfWcGae5NlhgetLNn0-3ZuM6GK8uQU',
    appId: '1:929662936824:ios:941d411cb12ffa35debd0d',
    messagingSenderId: '929662936824',
    projectId: 'easy-stock-micda-16001',
    storageBucket: 'easy-stock-micda-16001.firebasestorage.app',
    iosBundleId: 'com.example.easyStock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ9mfWcGae5NlhgetLNn0-3ZuM6GK8uQU',
    appId: '1:929662936824:ios:941d411cb12ffa35debd0d',
    messagingSenderId: '929662936824',
    projectId: 'easy-stock-micda-16001',
    storageBucket: 'easy-stock-micda-16001.firebasestorage.app',
    iosBundleId: 'com.example.easyStock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6d7Nq29h6FNB5mHu6qQErT-jRujb_cDE',
    appId: '1:929662936824:web:8caaa4b8b7fd05c7debd0d',
    messagingSenderId: '929662936824',
    projectId: 'easy-stock-micda-16001',
    authDomain: 'easy-stock-micda-16001.firebaseapp.com',
    storageBucket: 'easy-stock-micda-16001.firebasestorage.app',
  );

}